using UnityEngine;

public class CameraController : MonoBehaviour
{
    public Transform personaje;
    private float tama単oPantalla;
    private float alturaPantalla;
    void Start()
    {
        tama単oPantalla = Camera.main.orthographicSize;
        alturaPantalla = tama単oPantalla * 2;
    }

    void Update()
    {

    }

    void calcularPosicion()
    {
        int pantallaPersonaje = (int)(personaje.position.y / alturaPantalla);
        float alturaCamara = (pantallaPersonaje * alturaPantalla) + tama単oPantalla;

        transform.position = new Vector3(transform.position.x, alturaCamara, transform.position.z);
    }
}